# Generated by Django 3.2.13 on 2022-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_db_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('des', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('creater', models.IntegerField(default=0)),
            ],
        ),
    ]
