# Generated by Django 3.2.13 on 2022-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_db_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='L_data',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='Line',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='P_data',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='mock',
            field=models.CharField(blank=True, default='mock_data', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='power',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sign',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
