# Generated by Django 3.2.13 on 2022-06-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20220618_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
