# Generated by Django 3.2.13 on 2022-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_db_env_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_api_shop_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('host', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('path', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('params', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('paylod', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('headers', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('des', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
