# Generated by Django 3.2.13 on 2022-06-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_db_api_shop_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_api_shop_list',
            old_name='paylod',
            new_name='payload',
        ),
    ]
