# Generated by Django 3.2.13 on 2022-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_rename_paylod_db_api_shop_list_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_news',
            name='date',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
