# Generated by Django 3.2.13 on 2022-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_db_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_notice',
            name='date',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
