# Generated by Django 3.2.13 on 2022-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_auto_20220710_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='chose_apiconfigure',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='doing_api',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='email_to',
            field=models.CharField(blank=True, default='[]', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='end_result',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_host',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_pwd',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_project_list',
            name='sql_user',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
