# Generated by Django 3.2.13 on 2022-07-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_db_apis_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_apis',
            name='disabled',
        ),
    ]
