# Generated by Django 3.2.13 on 2022-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0020_auto_20220724_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='payload_binary',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
