# Generated by Django 3.2.13 on 2022-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_db_project_list_sql_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_api_shop_list',
            old_name='payload',
            new_name='payload_binary',
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='children',
            field=models.CharField(blank=True, default='[]', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='label',
            field=models.CharField(blank=True, default='新接口', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_GQL_g',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_GQL_q',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_fd',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_method',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_raw',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_raw_method',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='payload_xwfu',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='db_api_shop_list',
            name='type',
            field=models.CharField(blank=True, default='api', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='des',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='headers',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='host',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='method',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='params',
            field=models.CharField(blank=True, default='[]', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='db_api_shop_list',
            name='path',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
