# Generated by Django 3.2.13 on 2022-08-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_auto_20220807_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_api_shop_list',
            name='name',
        ),
    ]
