# Generated by Django 3.2.13 on 2022-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0029_db_project_list_catch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_news',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
