# Generated by Django 3.2.13 on 2022-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0030_db_news_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_run_counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('RunCase_count', models.IntegerField(default=0)),
                ('Import_count', models.IntegerField(default=0)),
            ],
        ),
    ]
